# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

# (Copyright) Bluerobin inc.
# Author: Minsu Kim < minsu309@bluerobin.co.kr, minsu309@snu.ac.kr >
# Description:

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(615, 781)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("BlueRobin_logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setEnabled(True)
        self.title.setGeometry(QtCore.QRect(65, 7, 351, 31))
        self.title.setScaledContents(False)
        self.title.setObjectName("title")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(20, 63, 281, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.push_connect = QtWidgets.QPushButton(self.frame)
        self.push_connect.setEnabled(True)
        self.push_connect.setGeometry(QtCore.QRect(10, 10, 101, 25))
        self.push_connect.setObjectName("push_connect")
        self.label_status = QtWidgets.QLabel(self.frame)
        self.label_status.setEnabled(True)
        self.label_status.setGeometry(QtCore.QRect(74, 44, 201, 20))
        self.label_status.setObjectName("label_status")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(14, 45, 67, 17))
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setEnabled(True)
        self.frame_3.setGeometry(QtCore.QRect(310, 63, 281, 71))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.push_disableall = QtWidgets.QPushButton(self.frame_3)
        self.push_disableall.setEnabled(False)
        self.push_disableall.setGeometry(QtCore.QRect(9, 39, 89, 25))
        self.push_disableall.setObjectName("push_disableall")
        self.push_enableall = QtWidgets.QPushButton(self.frame_3)
        self.push_enableall.setEnabled(False)
        self.push_enableall.setGeometry(QtCore.QRect(9, 9, 89, 25))
        self.push_enableall.setObjectName("push_enableall")
        self.push_cmd1 = QtWidgets.QPushButton(self.frame_3)
        self.push_cmd1.setEnabled(False)
        self.push_cmd1.setGeometry(QtCore.QRect(125, 10, 41, 51))
        self.push_cmd1.setObjectName("push_cmd1")
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setEnabled(True)
        self.line.setGeometry(QtCore.QRect(110, 6, 3, 61))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.push_cmd2 = QtWidgets.QPushButton(self.frame_3)
        self.push_cmd2.setEnabled(False)
        self.push_cmd2.setGeometry(QtCore.QRect(176, 10, 41, 51))
        self.push_cmd2.setObjectName("push_cmd2")
        self.push_cmd3 = QtWidgets.QPushButton(self.frame_3)
        self.push_cmd3.setEnabled(False)
        self.push_cmd3.setGeometry(QtCore.QRect(225, 10, 41, 51))
        self.push_cmd3.setObjectName("push_cmd3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(30, 46, 121, 17))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(320, 46, 121, 17))
        self.label_9.setObjectName("label_9")
        self.combo_reset = QtWidgets.QComboBox(self.centralwidget)
        self.combo_reset.setEnabled(False)
        self.combo_reset.setGeometry(QtCore.QRect(360, 140, 171, 25))
        self.combo_reset.setObjectName("combo_reset")
        self.combo_reset.addItem("")
        self.combo_reset.addItem("")
        self.combo_reset.addItem("")
        self.combo_reset.addItem("")
        self.combo_reset.addItem("")
        self.combo_reset.addItem("")
        self.combo_reset.addItem("")
        self.combo_reset.addItem("")
        self.combo_reset.addItem("")
        self.push_reset = QtWidgets.QPushButton(self.centralwidget)
        self.push_reset.setEnabled(False)
        self.push_reset.setGeometry(QtCore.QRect(540, 140, 51, 25))
        self.push_reset.setObjectName("push_reset")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(21, 7, 31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("BlueRobin_logo.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 625, 571, 131))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 569, 129))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_log = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_log.setLineWidth(0)
        self.label_log.setText("")
        self.label_log.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_log.setObjectName("label_log")
        self.verticalLayout.addWidget(self.label_log)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(20, 140, 571, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(2, 10, 561, 181))
        self.groupBox.setObjectName("groupBox")
        self.push_grip = QtWidgets.QPushButton(self.groupBox)
        self.push_grip.setEnabled(False)
        self.push_grip.setGeometry(QtCore.QRect(351, 38, 89, 91))
        self.push_grip.setObjectName("push_grip")
        self.push_release = QtWidgets.QPushButton(self.groupBox)
        self.push_release.setEnabled(False)
        self.push_release.setGeometry(QtCore.QRect(451, 38, 89, 91))
        self.push_release.setObjectName("push_release")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QtCore.QRect(180, 30, 151, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.push_strength1 = QtWidgets.QPushButton(self.groupBox_2)
        self.push_strength1.setGeometry(QtCore.QRect(5, 25, 43, 51))
        self.push_strength1.setObjectName("push_strength1")
        self.push_strength2 = QtWidgets.QPushButton(self.groupBox_2)
        self.push_strength2.setGeometry(QtCore.QRect(56, 25, 41, 51))
        self.push_strength2.setObjectName("push_strength2")
        self.push_strength3 = QtWidgets.QPushButton(self.groupBox_2)
        self.push_strength3.setGeometry(QtCore.QRect(104, 25, 41, 51))
        self.push_strength3.setObjectName("push_strength3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(50, 96, 51, 31))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.push_minus = QtWidgets.QPushButton(self.groupBox_2)
        self.push_minus.setGeometry(QtCore.QRect(7, 96, 41, 31))
        self.push_minus.setObjectName("push_minus")
        self.push_plus = QtWidgets.QPushButton(self.groupBox_2)
        self.push_plus.setGeometry(QtCore.QRect(104, 97, 41, 31))
        self.push_plus.setStyleSheet("")
        self.push_plus.setObjectName("push_plus")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 30, 151, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(6, 25, 141, 112))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check_target1 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_target1.setObjectName("check_target1")
        self.verticalLayout_2.addWidget(self.check_target1)
        self.check_target2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_target2.setObjectName("check_target2")
        self.verticalLayout_2.addWidget(self.check_target2)
        self.check_target3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_target3.setObjectName("check_target3")
        self.verticalLayout_2.addWidget(self.check_target3)
        self.check_target4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_target4.setObjectName("check_target4")
        self.verticalLayout_2.addWidget(self.check_target4)
        self.push_zero = QtWidgets.QPushButton(self.groupBox)
        self.push_zero.setEnabled(False)
        self.push_zero.setGeometry(QtCore.QRect(350, 136, 191, 31))
        self.push_zero.setObjectName("push_zero")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(2, 200, 561, 231))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_7.setEnabled(False)
        self.groupBox_7.setGeometry(QtCore.QRect(22, 40, 91, 171))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_8.setEnabled(False)
        self.groupBox_8.setGeometry(QtCore.QRect(370, 40, 81, 171))
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_cmd1 = QtWidgets.QLabel(self.groupBox_8)
        self.label_cmd1.setObjectName("label_cmd1")
        self.verticalLayout_8.addWidget(self.label_cmd1)
        self.label_cmd2 = QtWidgets.QLabel(self.groupBox_8)
        self.label_cmd2.setObjectName("label_cmd2")
        self.verticalLayout_8.addWidget(self.label_cmd2)
        self.label_cmd3 = QtWidgets.QLabel(self.groupBox_8)
        self.label_cmd3.setObjectName("label_cmd3")
        self.verticalLayout_8.addWidget(self.label_cmd3)
        self.label_cmd4 = QtWidgets.QLabel(self.groupBox_8)
        self.label_cmd4.setObjectName("label_cmd4")
        self.verticalLayout_8.addWidget(self.label_cmd4)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_9.setEnabled(False)
        self.groupBox_9.setGeometry(QtCore.QRect(462, 40, 81, 171))
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_real1 = QtWidgets.QLabel(self.groupBox_9)
        self.label_real1.setObjectName("label_real1")
        self.verticalLayout_9.addWidget(self.label_real1)
        self.label_real2 = QtWidgets.QLabel(self.groupBox_9)
        self.label_real2.setObjectName("label_real2")
        self.verticalLayout_9.addWidget(self.label_real2)
        self.label_real3 = QtWidgets.QLabel(self.groupBox_9)
        self.label_real3.setObjectName("label_real3")
        self.verticalLayout_9.addWidget(self.label_real3)
        self.label_real4 = QtWidgets.QLabel(self.groupBox_9)
        self.label_real4.setObjectName("label_real4")
        self.verticalLayout_9.addWidget(self.label_real4)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_10.setEnabled(False)
        self.groupBox_10.setGeometry(QtCore.QRect(121, 39, 241, 171))
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 3)
        self.verticalLayout_7.setSpacing(15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.slider_abd1 = QtWidgets.QSlider(self.groupBox_10)
        self.slider_abd1.setMaximum(100)
        self.slider_abd1.setPageStep(5)
        self.slider_abd1.setProperty("value", 50)
        self.slider_abd1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_abd1.setObjectName("slider_abd1")
        self.verticalLayout_7.addWidget(self.slider_abd1)
        self.slider_abd2 = QtWidgets.QSlider(self.groupBox_10)
        self.slider_abd2.setMaximum(100)
        self.slider_abd2.setPageStep(5)
        self.slider_abd2.setProperty("value", 50)
        self.slider_abd2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_abd2.setObjectName("slider_abd2")
        self.verticalLayout_7.addWidget(self.slider_abd2)
        self.slider_abd3 = QtWidgets.QSlider(self.groupBox_10)
        self.slider_abd3.setMaximum(100)
        self.slider_abd3.setPageStep(5)
        self.slider_abd3.setProperty("value", 50)
        self.slider_abd3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_abd3.setObjectName("slider_abd3")
        self.verticalLayout_7.addWidget(self.slider_abd3)
        self.slider_abd4 = QtWidgets.QSlider(self.groupBox_10)
        self.slider_abd4.setMaximum(100)
        self.slider_abd4.setPageStep(5)
        self.slider_abd4.setProperty("value", 50)
        self.slider_abd4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_abd4.setObjectName("slider_abd4")
        self.verticalLayout_7.addWidget(self.slider_abd4)
        self.groupBox_10.raise_()
        self.groupBox_7.raise_()
        self.groupBox_8.raise_()
        self.groupBox_9.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setEnabled(True)
        self.frame_2.setGeometry(QtCore.QRect(-1, 3, 571, 441))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widget_7 = QtWidgets.QWidget(self.frame_2)
        self.widget_7.setEnabled(True)
        self.widget_7.setGeometry(QtCore.QRect(289, 109, 279, 103))
        self.widget_7.setObjectName("widget_7")
        self.combo_mode6 = QtWidgets.QComboBox(self.widget_7)
        self.combo_mode6.setEnabled(False)
        self.combo_mode6.setGeometry(QtCore.QRect(172, 6, 86, 25))
        self.combo_mode6.setObjectName("combo_mode6")
        self.combo_mode6.addItem("")
        self.combo_mode6.addItem("")
        self.combo_mode6.addItem("")
        self.push_gain6 = QtWidgets.QPushButton(self.widget_7)
        self.push_gain6.setEnabled(False)
        self.push_gain6.setGeometry(QtCore.QRect(206, 35, 51, 25))
        self.push_gain6.setObjectName("push_gain6")
        self.radio_enable6 = QtWidgets.QRadioButton(self.widget_7)
        self.radio_enable6.setEnabled(False)
        self.radio_enable6.setGeometry(QtCore.QRect(17, 8, 151, 23))
        self.radio_enable6.setObjectName("radio_enable6")
        self.label_kp6 = QtWidgets.QLabel(self.widget_7)
        self.label_kp6.setEnabled(True)
        self.label_kp6.setGeometry(QtCore.QRect(18, 37, 21, 17))
        self.label_kp6.setObjectName("label_kp6")
        self.gain_kp6 = QtWidgets.QDoubleSpinBox(self.widget_7)
        self.gain_kp6.setEnabled(False)
        self.gain_kp6.setGeometry(QtCore.QRect(41, 34, 61, 26))
        self.gain_kp6.setMaximum(100000.0)
        self.gain_kp6.setSingleStep(10.0)
        self.gain_kp6.setObjectName("gain_kp6")
        self.label_kv6 = QtWidgets.QLabel(self.widget_7)
        self.label_kv6.setEnabled(True)
        self.label_kv6.setGeometry(QtCore.QRect(109, 38, 21, 17))
        self.label_kv6.setObjectName("label_kv6")
        self.gain_kv6 = QtWidgets.QDoubleSpinBox(self.widget_7)
        self.gain_kv6.setEnabled(False)
        self.gain_kv6.setGeometry(QtCore.QRect(132, 34, 61, 26))
        self.gain_kv6.setMaximum(100000.0)
        self.gain_kv6.setSingleStep(10.0)
        self.gain_kv6.setObjectName("gain_kv6")
        self.cur_val6 = QtWidgets.QLabel(self.widget_7)
        self.cur_val6.setEnabled(True)
        self.cur_val6.setGeometry(QtCore.QRect(209, 81, 51, 20))
        self.cur_val6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cur_val6.setObjectName("cur_val6")
        self.min_val6 = QtWidgets.QLabel(self.widget_7)
        self.min_val6.setEnabled(True)
        self.min_val6.setGeometry(QtCore.QRect(2, 68, 51, 17))
        self.min_val6.setAlignment(QtCore.Qt.AlignCenter)
        self.min_val6.setObjectName("min_val6")
        self.zero_val6 = QtWidgets.QLabel(self.widget_7)
        self.zero_val6.setEnabled(True)
        self.zero_val6.setGeometry(QtCore.QRect(80, 68, 51, 17))
        self.zero_val6.setAlignment(QtCore.Qt.AlignCenter)
        self.zero_val6.setObjectName("zero_val6")
        self.slider6 = QtWidgets.QSlider(self.widget_7)
        self.slider6.setEnabled(False)
        self.slider6.setGeometry(QtCore.QRect(19, 87, 171, 20))
        self.slider6.setMaximum(100)
        self.slider6.setPageStep(5)
        self.slider6.setProperty("value", 50)
        self.slider6.setOrientation(QtCore.Qt.Horizontal)
        self.slider6.setObjectName("slider6")
        self.max_val6 = QtWidgets.QLabel(self.widget_7)
        self.max_val6.setEnabled(True)
        self.max_val6.setGeometry(QtCore.QRect(160, 69, 51, 17))
        self.max_val6.setAlignment(QtCore.Qt.AlignCenter)
        self.max_val6.setObjectName("max_val6")
        self.widget_4 = QtWidgets.QWidget(self.frame_2)
        self.widget_4.setEnabled(True)
        self.widget_4.setGeometry(QtCore.QRect(-1, 330, 279, 104))
        self.widget_4.setObjectName("widget_4")
        self.combo_mode4 = QtWidgets.QComboBox(self.widget_4)
        self.combo_mode4.setEnabled(False)
        self.combo_mode4.setGeometry(QtCore.QRect(172, 6, 86, 25))
        self.combo_mode4.setObjectName("combo_mode4")
        self.combo_mode4.addItem("")
        self.combo_mode4.addItem("")
        self.combo_mode4.addItem("")
        self.push_gain4 = QtWidgets.QPushButton(self.widget_4)
        self.push_gain4.setEnabled(False)
        self.push_gain4.setGeometry(QtCore.QRect(206, 35, 51, 25))
        self.push_gain4.setObjectName("push_gain4")
        self.radio_enable4 = QtWidgets.QRadioButton(self.widget_4)
        self.radio_enable4.setEnabled(False)
        self.radio_enable4.setGeometry(QtCore.QRect(17, 7, 151, 23))
        self.radio_enable4.setObjectName("radio_enable4")
        self.label_kp4 = QtWidgets.QLabel(self.widget_4)
        self.label_kp4.setEnabled(True)
        self.label_kp4.setGeometry(QtCore.QRect(20, 37, 21, 17))
        self.label_kp4.setObjectName("label_kp4")
        self.label_kv4 = QtWidgets.QLabel(self.widget_4)
        self.label_kv4.setEnabled(True)
        self.label_kv4.setGeometry(QtCore.QRect(111, 38, 21, 17))
        self.label_kv4.setObjectName("label_kv4")
        self.gain_kv4 = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.gain_kv4.setEnabled(False)
        self.gain_kv4.setGeometry(QtCore.QRect(134, 34, 61, 26))
        self.gain_kv4.setMaximum(100000.0)
        self.gain_kv4.setSingleStep(10.0)
        self.gain_kv4.setObjectName("gain_kv4")
        self.gain_kp4 = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.gain_kp4.setEnabled(False)
        self.gain_kp4.setGeometry(QtCore.QRect(43, 34, 61, 26))
        self.gain_kp4.setMaximum(100000.0)
        self.gain_kp4.setSingleStep(10.0)
        self.gain_kp4.setObjectName("gain_kp4")
        self.cur_val4 = QtWidgets.QLabel(self.widget_4)
        self.cur_val4.setEnabled(True)
        self.cur_val4.setGeometry(QtCore.QRect(209, 79, 51, 20))
        self.cur_val4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cur_val4.setObjectName("cur_val4")
        self.min_val4 = QtWidgets.QLabel(self.widget_4)
        self.min_val4.setEnabled(True)
        self.min_val4.setGeometry(QtCore.QRect(2, 66, 51, 17))
        self.min_val4.setAlignment(QtCore.Qt.AlignCenter)
        self.min_val4.setObjectName("min_val4")
        self.zero_val4 = QtWidgets.QLabel(self.widget_4)
        self.zero_val4.setEnabled(True)
        self.zero_val4.setGeometry(QtCore.QRect(80, 66, 51, 17))
        self.zero_val4.setAlignment(QtCore.Qt.AlignCenter)
        self.zero_val4.setObjectName("zero_val4")
        self.slider4 = QtWidgets.QSlider(self.widget_4)
        self.slider4.setEnabled(False)
        self.slider4.setGeometry(QtCore.QRect(19, 85, 171, 20))
        self.slider4.setMaximum(100)
        self.slider4.setPageStep(5)
        self.slider4.setProperty("value", 50)
        self.slider4.setOrientation(QtCore.Qt.Horizontal)
        self.slider4.setObjectName("slider4")
        self.max_val4 = QtWidgets.QLabel(self.widget_4)
        self.max_val4.setEnabled(True)
        self.max_val4.setGeometry(QtCore.QRect(160, 67, 51, 17))
        self.max_val4.setAlignment(QtCore.Qt.AlignCenter)
        self.max_val4.setObjectName("max_val4")
        self.widget_6 = QtWidgets.QWidget(self.frame_2)
        self.widget_6.setEnabled(True)
        self.widget_6.setGeometry(QtCore.QRect(289, -1, 279, 104))
        self.widget_6.setObjectName("widget_6")
        self.combo_mode5 = QtWidgets.QComboBox(self.widget_6)
        self.combo_mode5.setEnabled(False)
        self.combo_mode5.setGeometry(QtCore.QRect(172, 6, 86, 25))
        self.combo_mode5.setObjectName("combo_mode5")
        self.combo_mode5.addItem("")
        self.combo_mode5.addItem("")
        self.combo_mode5.addItem("")
        self.push_gain5 = QtWidgets.QPushButton(self.widget_6)
        self.push_gain5.setEnabled(False)
        self.push_gain5.setGeometry(QtCore.QRect(206, 35, 51, 25))
        self.push_gain5.setObjectName("push_gain5")
        self.radio_enable5 = QtWidgets.QRadioButton(self.widget_6)
        self.radio_enable5.setEnabled(False)
        self.radio_enable5.setGeometry(QtCore.QRect(17, 8, 151, 23))
        self.radio_enable5.setObjectName("radio_enable5")
        self.label_kp5 = QtWidgets.QLabel(self.widget_6)
        self.label_kp5.setEnabled(True)
        self.label_kp5.setGeometry(QtCore.QRect(19, 37, 21, 17))
        self.label_kp5.setObjectName("label_kp5")
        self.gain_kp5 = QtWidgets.QDoubleSpinBox(self.widget_6)
        self.gain_kp5.setEnabled(False)
        self.gain_kp5.setGeometry(QtCore.QRect(42, 34, 61, 26))
        self.gain_kp5.setMaximum(100000.0)
        self.gain_kp5.setSingleStep(10.0)
        self.gain_kp5.setObjectName("gain_kp5")
        self.gain_kv5 = QtWidgets.QDoubleSpinBox(self.widget_6)
        self.gain_kv5.setEnabled(False)
        self.gain_kv5.setGeometry(QtCore.QRect(133, 34, 61, 26))
        self.gain_kv5.setMaximum(100000.0)
        self.gain_kv5.setSingleStep(10.0)
        self.gain_kv5.setObjectName("gain_kv5")
        self.label_kv5 = QtWidgets.QLabel(self.widget_6)
        self.label_kv5.setEnabled(True)
        self.label_kv5.setGeometry(QtCore.QRect(110, 38, 21, 17))
        self.label_kv5.setObjectName("label_kv5")
        self.max_val5 = QtWidgets.QLabel(self.widget_6)
        self.max_val5.setEnabled(True)
        self.max_val5.setGeometry(QtCore.QRect(160, 70, 51, 17))
        self.max_val5.setAlignment(QtCore.Qt.AlignCenter)
        self.max_val5.setObjectName("max_val5")
        self.zero_val5 = QtWidgets.QLabel(self.widget_6)
        self.zero_val5.setEnabled(True)
        self.zero_val5.setGeometry(QtCore.QRect(80, 69, 51, 17))
        self.zero_val5.setAlignment(QtCore.Qt.AlignCenter)
        self.zero_val5.setObjectName("zero_val5")
        self.slider5 = QtWidgets.QSlider(self.widget_6)
        self.slider5.setEnabled(False)
        self.slider5.setGeometry(QtCore.QRect(19, 88, 171, 20))
        self.slider5.setMaximum(100)
        self.slider5.setPageStep(5)
        self.slider5.setProperty("value", 50)
        self.slider5.setOrientation(QtCore.Qt.Horizontal)
        self.slider5.setObjectName("slider5")
        self.cur_val5 = QtWidgets.QLabel(self.widget_6)
        self.cur_val5.setEnabled(True)
        self.cur_val5.setGeometry(QtCore.QRect(209, 82, 51, 20))
        self.cur_val5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cur_val5.setObjectName("cur_val5")
        self.min_val5 = QtWidgets.QLabel(self.widget_6)
        self.min_val5.setEnabled(True)
        self.min_val5.setGeometry(QtCore.QRect(2, 69, 51, 17))
        self.min_val5.setAlignment(QtCore.Qt.AlignCenter)
        self.min_val5.setObjectName("min_val5")
        self.widget_3 = QtWidgets.QWidget(self.frame_2)
        self.widget_3.setEnabled(True)
        self.widget_3.setGeometry(QtCore.QRect(-1, 221, 279, 103))
        self.widget_3.setObjectName("widget_3")
        self.combo_mode3 = QtWidgets.QComboBox(self.widget_3)
        self.combo_mode3.setEnabled(False)
        self.combo_mode3.setGeometry(QtCore.QRect(172, 6, 86, 25))
        self.combo_mode3.setObjectName("combo_mode3")
        self.combo_mode3.addItem("")
        self.combo_mode3.addItem("")
        self.combo_mode3.addItem("")
        self.push_gain3 = QtWidgets.QPushButton(self.widget_3)
        self.push_gain3.setEnabled(False)
        self.push_gain3.setGeometry(QtCore.QRect(206, 35, 51, 25))
        self.push_gain3.setObjectName("push_gain3")
        self.radio_enable3 = QtWidgets.QRadioButton(self.widget_3)
        self.radio_enable3.setEnabled(False)
        self.radio_enable3.setGeometry(QtCore.QRect(17, 7, 151, 23))
        self.radio_enable3.setObjectName("radio_enable3")
        self.label_kp3 = QtWidgets.QLabel(self.widget_3)
        self.label_kp3.setEnabled(True)
        self.label_kp3.setGeometry(QtCore.QRect(20, 37, 21, 17))
        self.label_kp3.setObjectName("label_kp3")
        self.gain_kv3 = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.gain_kv3.setEnabled(False)
        self.gain_kv3.setGeometry(QtCore.QRect(134, 34, 61, 26))
        self.gain_kv3.setMaximum(100000.0)
        self.gain_kv3.setSingleStep(10.0)
        self.gain_kv3.setObjectName("gain_kv3")
        self.gain_kp3 = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.gain_kp3.setEnabled(False)
        self.gain_kp3.setGeometry(QtCore.QRect(43, 34, 61, 26))
        self.gain_kp3.setMaximum(100000.0)
        self.gain_kp3.setSingleStep(10.0)
        self.gain_kp3.setObjectName("gain_kp3")
        self.label_kv3 = QtWidgets.QLabel(self.widget_3)
        self.label_kv3.setEnabled(True)
        self.label_kv3.setGeometry(QtCore.QRect(111, 38, 21, 17))
        self.label_kv3.setObjectName("label_kv3")
        self.cur_val3 = QtWidgets.QLabel(self.widget_3)
        self.cur_val3.setEnabled(True)
        self.cur_val3.setGeometry(QtCore.QRect(209, 80, 51, 20))
        self.cur_val3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cur_val3.setObjectName("cur_val3")
        self.min_val3 = QtWidgets.QLabel(self.widget_3)
        self.min_val3.setEnabled(True)
        self.min_val3.setGeometry(QtCore.QRect(2, 67, 51, 17))
        self.min_val3.setAlignment(QtCore.Qt.AlignCenter)
        self.min_val3.setObjectName("min_val3")
        self.zero_val3 = QtWidgets.QLabel(self.widget_3)
        self.zero_val3.setEnabled(True)
        self.zero_val3.setGeometry(QtCore.QRect(80, 67, 51, 17))
        self.zero_val3.setAlignment(QtCore.Qt.AlignCenter)
        self.zero_val3.setObjectName("zero_val3")
        self.slider3 = QtWidgets.QSlider(self.widget_3)
        self.slider3.setEnabled(False)
        self.slider3.setGeometry(QtCore.QRect(19, 86, 171, 20))
        self.slider3.setMaximum(100)
        self.slider3.setPageStep(5)
        self.slider3.setProperty("value", 50)
        self.slider3.setOrientation(QtCore.Qt.Horizontal)
        self.slider3.setObjectName("slider3")
        self.max_val3 = QtWidgets.QLabel(self.widget_3)
        self.max_val3.setEnabled(True)
        self.max_val3.setGeometry(QtCore.QRect(160, 68, 51, 17))
        self.max_val3.setAlignment(QtCore.Qt.AlignCenter)
        self.max_val3.setObjectName("max_val3")
        self.widget_8 = QtWidgets.QWidget(self.frame_2)
        self.widget_8.setEnabled(True)
        self.widget_8.setGeometry(QtCore.QRect(288, 329, 279, 103))
        self.widget_8.setObjectName("widget_8")
        self.combo_mode8 = QtWidgets.QComboBox(self.widget_8)
        self.combo_mode8.setEnabled(False)
        self.combo_mode8.setGeometry(QtCore.QRect(172, 6, 86, 25))
        self.combo_mode8.setObjectName("combo_mode8")
        self.combo_mode8.addItem("")
        self.combo_mode8.addItem("")
        self.combo_mode8.addItem("")
        self.push_gain8 = QtWidgets.QPushButton(self.widget_8)
        self.push_gain8.setEnabled(False)
        self.push_gain8.setGeometry(QtCore.QRect(206, 35, 51, 25))
        self.push_gain8.setObjectName("push_gain8")
        self.radio_enable8 = QtWidgets.QRadioButton(self.widget_8)
        self.radio_enable8.setEnabled(False)
        self.radio_enable8.setGeometry(QtCore.QRect(19, 7, 151, 23))
        self.radio_enable8.setObjectName("radio_enable8")
        self.label_kp8 = QtWidgets.QLabel(self.widget_8)
        self.label_kp8.setEnabled(True)
        self.label_kp8.setGeometry(QtCore.QRect(22, 36, 21, 17))
        self.label_kp8.setObjectName("label_kp8")
        self.gain_kv8 = QtWidgets.QDoubleSpinBox(self.widget_8)
        self.gain_kv8.setEnabled(False)
        self.gain_kv8.setGeometry(QtCore.QRect(136, 33, 61, 26))
        self.gain_kv8.setMaximum(100000.0)
        self.gain_kv8.setSingleStep(10.0)
        self.gain_kv8.setObjectName("gain_kv8")
        self.label_kv8 = QtWidgets.QLabel(self.widget_8)
        self.label_kv8.setEnabled(True)
        self.label_kv8.setGeometry(QtCore.QRect(113, 37, 21, 17))
        self.label_kv8.setObjectName("label_kv8")
        self.gain_kp8 = QtWidgets.QDoubleSpinBox(self.widget_8)
        self.gain_kp8.setEnabled(False)
        self.gain_kp8.setGeometry(QtCore.QRect(45, 33, 61, 26))
        self.gain_kp8.setMaximum(100000.0)
        self.gain_kp8.setSingleStep(10.0)
        self.gain_kp8.setObjectName("gain_kp8")
        self.cur_val8 = QtWidgets.QLabel(self.widget_8)
        self.cur_val8.setEnabled(True)
        self.cur_val8.setGeometry(QtCore.QRect(211, 79, 51, 20))
        self.cur_val8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cur_val8.setObjectName("cur_val8")
        self.min_val8 = QtWidgets.QLabel(self.widget_8)
        self.min_val8.setEnabled(True)
        self.min_val8.setGeometry(QtCore.QRect(4, 66, 51, 17))
        self.min_val8.setAlignment(QtCore.Qt.AlignCenter)
        self.min_val8.setObjectName("min_val8")
        self.zero_val8 = QtWidgets.QLabel(self.widget_8)
        self.zero_val8.setEnabled(True)
        self.zero_val8.setGeometry(QtCore.QRect(82, 66, 51, 17))
        self.zero_val8.setAlignment(QtCore.Qt.AlignCenter)
        self.zero_val8.setObjectName("zero_val8")
        self.slider8 = QtWidgets.QSlider(self.widget_8)
        self.slider8.setEnabled(False)
        self.slider8.setGeometry(QtCore.QRect(21, 85, 171, 20))
        self.slider8.setMaximum(100)
        self.slider8.setPageStep(5)
        self.slider8.setProperty("value", 50)
        self.slider8.setOrientation(QtCore.Qt.Horizontal)
        self.slider8.setObjectName("slider8")
        self.max_val8 = QtWidgets.QLabel(self.widget_8)
        self.max_val8.setEnabled(True)
        self.max_val8.setGeometry(QtCore.QRect(162, 67, 51, 17))
        self.max_val8.setAlignment(QtCore.Qt.AlignCenter)
        self.max_val8.setObjectName("max_val8")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(-1, 2, 279, 103))
        self.widget.setObjectName("widget")
        self.combo_mode1 = QtWidgets.QComboBox(self.widget)
        self.combo_mode1.setEnabled(False)
        self.combo_mode1.setGeometry(QtCore.QRect(172, 4, 86, 25))
        self.combo_mode1.setObjectName("combo_mode1")
        self.combo_mode1.addItem("")
        self.combo_mode1.addItem("")
        self.combo_mode1.addItem("")
        self.min_val1 = QtWidgets.QLabel(self.widget)
        self.min_val1.setEnabled(True)
        self.min_val1.setGeometry(QtCore.QRect(0, 67, 51, 17))
        self.min_val1.setAlignment(QtCore.Qt.AlignCenter)
        self.min_val1.setObjectName("min_val1")
        self.max_val1 = QtWidgets.QLabel(self.widget)
        self.max_val1.setEnabled(True)
        self.max_val1.setGeometry(QtCore.QRect(158, 68, 51, 17))
        self.max_val1.setAlignment(QtCore.Qt.AlignCenter)
        self.max_val1.setObjectName("max_val1")
        self.label_kv1 = QtWidgets.QLabel(self.widget)
        self.label_kv1.setEnabled(True)
        self.label_kv1.setGeometry(QtCore.QRect(109, 38, 21, 17))
        self.label_kv1.setObjectName("label_kv1")
        self.slider1 = QtWidgets.QSlider(self.widget)
        self.slider1.setEnabled(False)
        self.slider1.setGeometry(QtCore.QRect(17, 86, 171, 20))
        self.slider1.setMinimum(0)
        self.slider1.setMaximum(100)
        self.slider1.setPageStep(5)
        self.slider1.setProperty("value", 50)
        self.slider1.setOrientation(QtCore.Qt.Horizontal)
        self.slider1.setObjectName("slider1")
        self.label_kp1 = QtWidgets.QLabel(self.widget)
        self.label_kp1.setEnabled(True)
        self.label_kp1.setGeometry(QtCore.QRect(18, 37, 21, 17))
        self.label_kp1.setObjectName("label_kp1")
        self.push_gain1 = QtWidgets.QPushButton(self.widget)
        self.push_gain1.setEnabled(False)
        self.push_gain1.setGeometry(QtCore.QRect(206, 35, 51, 25))
        self.push_gain1.setObjectName("push_gain1")
        self.radio_enable1 = QtWidgets.QRadioButton(self.widget)
        self.radio_enable1.setEnabled(False)
        self.radio_enable1.setGeometry(QtCore.QRect(17, 5, 151, 23))
        self.radio_enable1.setObjectName("radio_enable1")
        self.gain_kp1 = QtWidgets.QDoubleSpinBox(self.widget)
        self.gain_kp1.setEnabled(False)
        self.gain_kp1.setGeometry(QtCore.QRect(41, 34, 61, 26))
        self.gain_kp1.setDecimals(2)
        self.gain_kp1.setMaximum(100000.0)
        self.gain_kp1.setSingleStep(10.0)
        self.gain_kp1.setObjectName("gain_kp1")
        self.gain_kv1 = QtWidgets.QDoubleSpinBox(self.widget)
        self.gain_kv1.setEnabled(False)
        self.gain_kv1.setGeometry(QtCore.QRect(132, 34, 61, 26))
        self.gain_kv1.setMaximum(100000.0)
        self.gain_kv1.setSingleStep(10.0)
        self.gain_kv1.setObjectName("gain_kv1")
        self.cur_val1 = QtWidgets.QLabel(self.widget)
        self.cur_val1.setEnabled(True)
        self.cur_val1.setGeometry(QtCore.QRect(207, 80, 51, 20))
        self.cur_val1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cur_val1.setObjectName("cur_val1")
        self.zero_val1 = QtWidgets.QLabel(self.widget)
        self.zero_val1.setEnabled(True)
        self.zero_val1.setGeometry(QtCore.QRect(78, 67, 51, 17))
        self.zero_val1.setAlignment(QtCore.Qt.AlignCenter)
        self.zero_val1.setObjectName("zero_val1")
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setEnabled(True)
        self.widget_2.setGeometry(QtCore.QRect(-1, 111, 279, 104))
        self.widget_2.setObjectName("widget_2")
        self.combo_mode2 = QtWidgets.QComboBox(self.widget_2)
        self.combo_mode2.setEnabled(False)
        self.combo_mode2.setGeometry(QtCore.QRect(172, 6, 86, 25))
        self.combo_mode2.setObjectName("combo_mode2")
        self.combo_mode2.addItem("")
        self.combo_mode2.addItem("")
        self.combo_mode2.addItem("")
        self.push_gain2 = QtWidgets.QPushButton(self.widget_2)
        self.push_gain2.setEnabled(False)
        self.push_gain2.setGeometry(QtCore.QRect(206, 35, 51, 25))
        self.push_gain2.setObjectName("push_gain2")
        self.radio_enable2 = QtWidgets.QRadioButton(self.widget_2)
        self.radio_enable2.setEnabled(False)
        self.radio_enable2.setGeometry(QtCore.QRect(17, 7, 151, 23))
        self.radio_enable2.setObjectName("radio_enable2")
        self.label_kp2 = QtWidgets.QLabel(self.widget_2)
        self.label_kp2.setEnabled(True)
        self.label_kp2.setGeometry(QtCore.QRect(19, 37, 21, 17))
        self.label_kp2.setObjectName("label_kp2")
        self.gain_kp2 = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.gain_kp2.setEnabled(False)
        self.gain_kp2.setGeometry(QtCore.QRect(42, 34, 61, 26))
        self.gain_kp2.setMaximum(100000.0)
        self.gain_kp2.setSingleStep(10.0)
        self.gain_kp2.setObjectName("gain_kp2")
        self.gain_kv2 = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.gain_kv2.setEnabled(False)
        self.gain_kv2.setGeometry(QtCore.QRect(133, 34, 61, 26))
        self.gain_kv2.setMaximum(100000.0)
        self.gain_kv2.setSingleStep(10.0)
        self.gain_kv2.setObjectName("gain_kv2")
        self.label_kv2 = QtWidgets.QLabel(self.widget_2)
        self.label_kv2.setEnabled(True)
        self.label_kv2.setGeometry(QtCore.QRect(110, 38, 21, 17))
        self.label_kv2.setObjectName("label_kv2")
        self.cur_val2 = QtWidgets.QLabel(self.widget_2)
        self.cur_val2.setEnabled(True)
        self.cur_val2.setGeometry(QtCore.QRect(209, 82, 51, 20))
        self.cur_val2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cur_val2.setObjectName("cur_val2")
        self.min_val2 = QtWidgets.QLabel(self.widget_2)
        self.min_val2.setEnabled(True)
        self.min_val2.setGeometry(QtCore.QRect(2, 69, 51, 17))
        self.min_val2.setAlignment(QtCore.Qt.AlignCenter)
        self.min_val2.setObjectName("min_val2")
        self.zero_val2 = QtWidgets.QLabel(self.widget_2)
        self.zero_val2.setEnabled(True)
        self.zero_val2.setGeometry(QtCore.QRect(80, 69, 51, 17))
        self.zero_val2.setAlignment(QtCore.Qt.AlignCenter)
        self.zero_val2.setObjectName("zero_val2")
        self.slider2 = QtWidgets.QSlider(self.widget_2)
        self.slider2.setEnabled(False)
        self.slider2.setGeometry(QtCore.QRect(19, 88, 171, 20))
        self.slider2.setMaximum(100)
        self.slider2.setPageStep(5)
        self.slider2.setProperty("value", 50)
        self.slider2.setOrientation(QtCore.Qt.Horizontal)
        self.slider2.setObjectName("slider2")
        self.max_val2 = QtWidgets.QLabel(self.widget_2)
        self.max_val2.setEnabled(True)
        self.max_val2.setGeometry(QtCore.QRect(160, 70, 51, 17))
        self.max_val2.setAlignment(QtCore.Qt.AlignCenter)
        self.max_val2.setObjectName("max_val2")
        self.widget_5 = QtWidgets.QWidget(self.frame_2)
        self.widget_5.setEnabled(True)
        self.widget_5.setGeometry(QtCore.QRect(288, 220, 279, 103))
        self.widget_5.setObjectName("widget_5")
        self.combo_mode7 = QtWidgets.QComboBox(self.widget_5)
        self.combo_mode7.setEnabled(False)
        self.combo_mode7.setGeometry(QtCore.QRect(172, 6, 86, 25))
        self.combo_mode7.setObjectName("combo_mode7")
        self.combo_mode7.addItem("")
        self.combo_mode7.addItem("")
        self.combo_mode7.addItem("")
        self.push_gain7 = QtWidgets.QPushButton(self.widget_5)
        self.push_gain7.setEnabled(False)
        self.push_gain7.setGeometry(QtCore.QRect(206, 35, 51, 25))
        self.push_gain7.setObjectName("push_gain7")
        self.radio_enable7 = QtWidgets.QRadioButton(self.widget_5)
        self.radio_enable7.setEnabled(False)
        self.radio_enable7.setGeometry(QtCore.QRect(19, 6, 151, 23))
        self.radio_enable7.setObjectName("radio_enable7")
        self.label_kp7 = QtWidgets.QLabel(self.widget_5)
        self.label_kp7.setEnabled(True)
        self.label_kp7.setGeometry(QtCore.QRect(21, 36, 21, 17))
        self.label_kp7.setObjectName("label_kp7")
        self.gain_kv7 = QtWidgets.QDoubleSpinBox(self.widget_5)
        self.gain_kv7.setEnabled(False)
        self.gain_kv7.setGeometry(QtCore.QRect(135, 33, 61, 26))
        self.gain_kv7.setMaximum(100000.0)
        self.gain_kv7.setSingleStep(10.0)
        self.gain_kv7.setObjectName("gain_kv7")
        self.label_kv7 = QtWidgets.QLabel(self.widget_5)
        self.label_kv7.setEnabled(True)
        self.label_kv7.setGeometry(QtCore.QRect(112, 37, 21, 17))
        self.label_kv7.setObjectName("label_kv7")
        self.gain_kp7 = QtWidgets.QDoubleSpinBox(self.widget_5)
        self.gain_kp7.setEnabled(False)
        self.gain_kp7.setGeometry(QtCore.QRect(44, 33, 61, 26))
        self.gain_kp7.setMaximum(100000.0)
        self.gain_kp7.setSingleStep(10.0)
        self.gain_kp7.setObjectName("gain_kp7")
        self.cur_val7 = QtWidgets.QLabel(self.widget_5)
        self.cur_val7.setEnabled(True)
        self.cur_val7.setGeometry(QtCore.QRect(209, 81, 51, 20))
        self.cur_val7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cur_val7.setObjectName("cur_val7")
        self.min_val7 = QtWidgets.QLabel(self.widget_5)
        self.min_val7.setEnabled(True)
        self.min_val7.setGeometry(QtCore.QRect(2, 68, 51, 17))
        self.min_val7.setAlignment(QtCore.Qt.AlignCenter)
        self.min_val7.setObjectName("min_val7")
        self.zero_val7 = QtWidgets.QLabel(self.widget_5)
        self.zero_val7.setEnabled(True)
        self.zero_val7.setGeometry(QtCore.QRect(80, 68, 51, 17))
        self.zero_val7.setAlignment(QtCore.Qt.AlignCenter)
        self.zero_val7.setObjectName("zero_val7")
        self.slider7 = QtWidgets.QSlider(self.widget_5)
        self.slider7.setEnabled(False)
        self.slider7.setGeometry(QtCore.QRect(19, 87, 171, 20))
        self.slider7.setMaximum(100)
        self.slider7.setPageStep(5)
        self.slider7.setProperty("value", 50)
        self.slider7.setOrientation(QtCore.Qt.Horizontal)
        self.slider7.setObjectName("slider7")
        self.max_val7 = QtWidgets.QLabel(self.widget_5)
        self.max_val7.setEnabled(True)
        self.max_val7.setGeometry(QtCore.QRect(160, 69, 51, 17))
        self.max_val7.setAlignment(QtCore.Qt.AlignCenter)
        self.max_val7.setObjectName("max_val7")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setEnabled(True)
        self.line_2.setGeometry(QtCore.QRect(277, 0, 16, 441))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setEnabled(True)
        self.line_3.setGeometry(QtCore.QRect(0, 212, 561, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tabWidget.raise_()
        self.frame_3.raise_()
        self.frame.raise_()
        self.title.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.combo_reset.raise_()
        self.push_reset.raise_()
        self.label.raise_()
        self.scrollArea.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BRHand Controller"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">BRHand Controller v1.0.1</span></p></body></html>"))
        self.push_connect.setText(_translate("MainWindow", "ROS Connect"))
        self.label_status.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Not Connected</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Status :"))
        self.push_disableall.setText(_translate("MainWindow", "Disable All"))
        self.push_enableall.setText(_translate("MainWindow", "Enable All"))
        self.push_cmd1.setText(_translate("MainWindow", "1"))
        self.push_cmd2.setText(_translate("MainWindow", "2"))
        self.push_cmd3.setText(_translate("MainWindow", "3"))
        self.label_7.setText(_translate("MainWindow", "Communication"))
        self.label_9.setText(_translate("MainWindow", "Preset Command"))
        self.combo_reset.setItemText(0, _translate("MainWindow", "None"))
        self.combo_reset.setItemText(1, _translate("MainWindow", "Thumb - Add./Abd."))
        self.combo_reset.setItemText(2, _translate("MainWindow", "Thumb - Flex./Ext."))
        self.combo_reset.setItemText(3, _translate("MainWindow", "Index - Add./Abd."))
        self.combo_reset.setItemText(4, _translate("MainWindow", "Index - Flex./Ext."))
        self.combo_reset.setItemText(5, _translate("MainWindow", "Middle - Add./Abd."))
        self.combo_reset.setItemText(6, _translate("MainWindow", "Middle - Flex./Ext."))
        self.combo_reset.setItemText(7, _translate("MainWindow", "Ring - Add./Abd."))
        self.combo_reset.setItemText(8, _translate("MainWindow", "Ring - Flex./Ext."))
        self.push_reset.setText(_translate("MainWindow", "reset"))
        self.groupBox.setTitle(_translate("MainWindow", "Flexion / Extension Control"))
        self.push_grip.setText(_translate("MainWindow", "Grip"))
        self.push_release.setText(_translate("MainWindow", "Release"))
        self.groupBox_2.setTitle(_translate("MainWindow", "strength"))
        self.push_strength1.setText(_translate("MainWindow", "1"))
        self.push_strength2.setText(_translate("MainWindow", "2"))
        self.push_strength3.setText(_translate("MainWindow", "3"))
        self.label_8.setText(_translate("MainWindow", "0"))
        self.push_minus.setText(_translate("MainWindow", "-"))
        self.push_plus.setText(_translate("MainWindow", "+"))
        self.groupBox_3.setTitle(_translate("MainWindow", "target"))
        self.check_target1.setText(_translate("MainWindow", "Thumb"))
        self.check_target2.setText(_translate("MainWindow", "Index"))
        self.check_target3.setText(_translate("MainWindow", "Middle"))
        self.check_target4.setText(_translate("MainWindow", "Ring"))
        self.push_zero.setText(_translate("MainWindow", "Zero"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Adduction / Abduction Control"))
        self.groupBox_7.setTitle(_translate("MainWindow", "target"))
        self.label_3.setText(_translate("MainWindow", "Thumb"))
        self.label_4.setText(_translate("MainWindow", "Index"))
        self.label_5.setText(_translate("MainWindow", "Middle"))
        self.label_6.setText(_translate("MainWindow", "Ring"))
        self.groupBox_8.setTitle(_translate("MainWindow", "cmd"))
        self.label_cmd1.setText(_translate("MainWindow", "0"))
        self.label_cmd2.setText(_translate("MainWindow", "0"))
        self.label_cmd3.setText(_translate("MainWindow", "0"))
        self.label_cmd4.setText(_translate("MainWindow", "0"))
        self.groupBox_9.setTitle(_translate("MainWindow", "real value"))
        self.label_real1.setText(_translate("MainWindow", "0"))
        self.label_real2.setText(_translate("MainWindow", "0"))
        self.label_real3.setText(_translate("MainWindow", "0"))
        self.label_real4.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "basic"))
        self.combo_mode6.setItemText(0, _translate("MainWindow", "Current"))
        self.combo_mode6.setItemText(1, _translate("MainWindow", "Position"))
        self.combo_mode6.setItemText(2, _translate("MainWindow", "PD"))
        self.push_gain6.setText(_translate("MainWindow", "send"))
        self.radio_enable6.setText(_translate("MainWindow", "Middle - Flex./ext."))
        self.label_kp6.setText(_translate("MainWindow", "Kp"))
        self.label_kv6.setText(_translate("MainWindow", "Kv"))
        self.cur_val6.setText(_translate("MainWindow", "0"))
        self.min_val6.setText(_translate("MainWindow", "-200"))
        self.zero_val6.setText(_translate("MainWindow", "0"))
        self.max_val6.setText(_translate("MainWindow", "200"))
        self.combo_mode4.setItemText(0, _translate("MainWindow", "Current"))
        self.combo_mode4.setItemText(1, _translate("MainWindow", "Position"))
        self.combo_mode4.setItemText(2, _translate("MainWindow", "PD"))
        self.push_gain4.setText(_translate("MainWindow", "send"))
        self.radio_enable4.setText(_translate("MainWindow", "Index - Flex./ext."))
        self.label_kp4.setText(_translate("MainWindow", "Kp"))
        self.label_kv4.setText(_translate("MainWindow", "Kv"))
        self.cur_val4.setText(_translate("MainWindow", "0"))
        self.min_val4.setText(_translate("MainWindow", "-200"))
        self.zero_val4.setText(_translate("MainWindow", "0"))
        self.max_val4.setText(_translate("MainWindow", "200"))
        self.combo_mode5.setItemText(0, _translate("MainWindow", "Current"))
        self.combo_mode5.setItemText(1, _translate("MainWindow", "Position"))
        self.combo_mode5.setItemText(2, _translate("MainWindow", "PD"))
        self.push_gain5.setText(_translate("MainWindow", "send"))
        self.radio_enable5.setText(_translate("MainWindow", "Middle -  Add./Abd."))
        self.label_kp5.setText(_translate("MainWindow", "Kp"))
        self.label_kv5.setText(_translate("MainWindow", "Kv"))
        self.max_val5.setText(_translate("MainWindow", "200"))
        self.zero_val5.setText(_translate("MainWindow", "0"))
        self.cur_val5.setText(_translate("MainWindow", "0"))
        self.min_val5.setText(_translate("MainWindow", "-200"))
        self.combo_mode3.setItemText(0, _translate("MainWindow", "Current"))
        self.combo_mode3.setItemText(1, _translate("MainWindow", "Position"))
        self.combo_mode3.setItemText(2, _translate("MainWindow", "PD"))
        self.push_gain3.setText(_translate("MainWindow", "send"))
        self.radio_enable3.setText(_translate("MainWindow", "Index -  Add./Abd."))
        self.label_kp3.setText(_translate("MainWindow", "Kp"))
        self.label_kv3.setText(_translate("MainWindow", "Kv"))
        self.cur_val3.setText(_translate("MainWindow", "0"))
        self.min_val3.setText(_translate("MainWindow", "-200"))
        self.zero_val3.setText(_translate("MainWindow", "0"))
        self.max_val3.setText(_translate("MainWindow", "200"))
        self.combo_mode8.setItemText(0, _translate("MainWindow", "Current"))
        self.combo_mode8.setItemText(1, _translate("MainWindow", "Position"))
        self.combo_mode8.setItemText(2, _translate("MainWindow", "PD"))
        self.push_gain8.setText(_translate("MainWindow", "send"))
        self.radio_enable8.setText(_translate("MainWindow", "Ring - Flex./ext."))
        self.label_kp8.setText(_translate("MainWindow", "Kp"))
        self.label_kv8.setText(_translate("MainWindow", "Kv"))
        self.cur_val8.setText(_translate("MainWindow", "0"))
        self.min_val8.setText(_translate("MainWindow", "-200"))
        self.zero_val8.setText(_translate("MainWindow", "0"))
        self.max_val8.setText(_translate("MainWindow", "200"))
        self.combo_mode1.setItemText(0, _translate("MainWindow", "Current"))
        self.combo_mode1.setItemText(1, _translate("MainWindow", "Position"))
        self.combo_mode1.setItemText(2, _translate("MainWindow", "PD"))
        self.min_val1.setText(_translate("MainWindow", "-200"))
        self.max_val1.setText(_translate("MainWindow", "200"))
        self.label_kv1.setText(_translate("MainWindow", "Kv"))
        self.label_kp1.setText(_translate("MainWindow", "Kp"))
        self.push_gain1.setText(_translate("MainWindow", "send"))
        self.radio_enable1.setText(_translate("MainWindow", "Thumb - Add./Abd."))
        self.cur_val1.setText(_translate("MainWindow", "0"))
        self.zero_val1.setText(_translate("MainWindow", "0"))
        self.combo_mode2.setItemText(0, _translate("MainWindow", "Current"))
        self.combo_mode2.setItemText(1, _translate("MainWindow", "Position"))
        self.combo_mode2.setItemText(2, _translate("MainWindow", "PD"))
        self.push_gain2.setText(_translate("MainWindow", "send"))
        self.radio_enable2.setText(_translate("MainWindow", "Thumb - Flex./ext."))
        self.label_kp2.setText(_translate("MainWindow", "Kp"))
        self.label_kv2.setText(_translate("MainWindow", "Kv"))
        self.cur_val2.setText(_translate("MainWindow", "0"))
        self.min_val2.setText(_translate("MainWindow", "-200"))
        self.zero_val2.setText(_translate("MainWindow", "0"))
        self.max_val2.setText(_translate("MainWindow", "200"))
        self.combo_mode7.setItemText(0, _translate("MainWindow", "Current"))
        self.combo_mode7.setItemText(1, _translate("MainWindow", "Position"))
        self.combo_mode7.setItemText(2, _translate("MainWindow", "PD"))
        self.push_gain7.setText(_translate("MainWindow", "send"))
        self.radio_enable7.setText(_translate("MainWindow", "Ring -  Add./Abd."))
        self.label_kp7.setText(_translate("MainWindow", "Kp"))
        self.label_kv7.setText(_translate("MainWindow", "Kv"))
        self.cur_val7.setText(_translate("MainWindow", "0"))
        self.min_val7.setText(_translate("MainWindow", "-200"))
        self.zero_val7.setText(_translate("MainWindow", "0"))
        self.max_val7.setText(_translate("MainWindow", "200"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "advanced"))
